name: Build project

on:
  push:
    branches:
    - main
    paths:
    - Source/**
  pull_request:
    branches:
    - main
    paths:
    - Source/**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Build release
      run: msbuild Source/GrasscutterTools.sln /p:Configuration=Release
    
    - name: Create zip
      run: Compress-Archive Source/GrasscutterTools/bin/Release/GrasscutterTools.exe GrasscutterTools.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GrasscutterTools
        path: GrasscutterTools.zip
